import type { Metadata } from 'next'
import { Inter, M_PLUS_Rounded_1c, Poppins } from 'next/font/google'
import './globals.css'

export const metadata: Metadata = {
  title: 'Krish vishwakarma',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
