import type { Metadata } from 'next'
import { Inter, M_PLUS_Rounded_1c, Poppins } from 'next/font/google'
import './globals.css'

const mplus = M_PLUS_Rounded_1c({subsets:["cyrillic"], weight:["100","300","400","700","800"]})
const poppins = Poppins({subsets:['latin'], weight:["200","400","600","700"]})
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
